routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CatalogController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;

Route::get('/', function () {
    return view('default');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware('auth')->resource('products', ProductController::class);
// Route::middleware('auth')->resource('cart', CartController::class);

Route::resource('catalog', CatalogController::class);
Route::post('/catalog/add/{id}', [CatalogController::class, 'add'])->name('catalog.add');
Route::post('/catalog', [CatalogController::class, 'index'])->name('catalog');

Route::get('/cart', [CartController::class, 'index'])->name('cart');
Route::get('/cart/increase/{id}', [CartController::class, 'increase'])->name('cart.increase');
Route::get('/cart/decrease/{id}', [CartController::class, 'decrease'])->name('cart.decrease');
Route::get('/cart/delete/{id}', [CartController::class, 'delete'])->name('cart.delete');


require __DIR__.'/auth.php';

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Http\Services\CartService;

class CatalogController extends Controller
{
    public function __construct(private CartService $cartService)
    {
        $this->cartService = $cartService;
    }

    public function index()
    {
        $products = Product::latest()->paginate(5);
        $cart = $this->cartService->getFull();

        return view('catalog.index', compact('products', 'cart'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function add($id)
    {
        $this->cartService->add($id);
        return redirect()->route('catalog.index');
    }

    
}

app/View/Components/DefaultLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class DefaultLayout extends Component
{
    public function render()
    {
        return view('layouts.default');
    }
}

resources/views/catalog/detail.blade.php
@extends('catalog.layout')

@section('content')

@endsection

resources/views/catalog/index.blade.php
@extends('catalog.layout')

@section('content')
<div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="text-2xl font-bold tracking-tight text-gray-900">Customers also purchased</h2>

    @foreach($products as $product)
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
        <div class="group relative">
            <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                <img src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg" alt="Front of men&#039;s Basic Tee in black." class="h-full w-full object-cover object-center lg:h-full lg:w-full">
            </div>
            <div class="mt-4 flex justify-between">
                <div>
                    <h3 class="text-sm text-gray-700">
                        <a href="#">
                            {{ $product->title }}
                        </a>
                    </h3>
                    <p class="mt-1 text-sm text-gray-500">Il reste {{ $product->quantity }}</p>
                </div>
                <p class="text-sm font-medium text-gray-900">{{ $product->price }} €</p>
            </div>
            <form action="{{ route('catalog.add', $product->id) }}" class="mt-3" method="POST">
                @csrf
                <button type="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 dark:bg-gray-200 border border-transparent rounded-md font-semibold text-xs text-white dark:text-gray-800 uppercase tracking-widest hover:bg-gray-700 dark:hover:bg-white focus:bg-gray-700 dark:focus:bg-white active:bg-gray-900 dark:active:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800 transition ease-in-out duration-150">Ajouter au panier</button>
            </form>
        </div>
    </div>
    @endforeach
</div>

@endsection

resources/views/catalog/layout.blade.php
<x-default-layout>
    @yield('content')
</x-default-layout>